# Minigames Config

Lava-Survival:
  original-world: "world" # The name of the world where the players will get teleport back when they quit the game
  original-world-coords:
    x: 0
    y: 0
    z: 0
  lobby: "lobby" # The name of the world where the players will get teleport into while waiting for the game to start
  lobby-coords:
    x: 0
    y: 0
    z: 0
  map-names: # Map names that you should add below it
    - "map1"
    - "map2"
    - "map3"
  map1: # -> Match the map names you just typed above (The map name will also be displayed in game!)
    world: "map1" # The name of the world where the players will play the game in
    world-coords: # The coord in the world where the players will teleport to when the game start
      x: 0
      y: 0
      z: 0
    first-coords: # Lava will be filled between first and second coordinate
      x: 0
      y: 0
      z: 0
    second-coords: # Barrier will be set under the lava and removed when the lava is released
      x: 0
      y: 0
      z: 0
    third-coords: # The area between the first coords and third coords will be cleared after a game is finished
      x: 0 # -> should be the same as the second coords x
      y: 0 # -> should be ground level
      z: 0 # -> should be the same as the second coords z

  map2: # -> Match the map names you just typed above (The map name will also be displayed in game!)
    world: "map2"
    world-coords:
      x: 0
      y: 0
      z: 0
    first-coords:
      x: 0
      y: 0
      z: 0
    second-coords:
      x: 0
      y: 0
      z: 0
    third-coords:
      x: 0
      y: 0
      z: 0

  map3: # -> Match the map names you just typed above (The map name will also be displayed in game!)
    world: "map3"
    world-coords:
      x: 0
      y: 0
      z: 0
    first-coords:
      x: 0
      y: 0
      z: 0
    second-coords:
      x: 0
      y: 0
      z: 0
    third-coords:
      x: 0
      y: 0
      z: 0

  min-player: 2  # The minimum players required to start the game
  max-player: 12 # The maximum players that can join in a game
  countdown: 120 # seconds the game will wait before starting if reach minimum players needed
  building-time: 180 # how many seconds players can build before the lava start pouring down
  starting-item:
  # Please enter valid material ID (All the material ID is in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
    - "WHITE_WOOL"
    - "OAK_LOG"
    - "SHEARS"
    - "IRON_AXE"
  item-amount: # Enter the exact order following the item above
    - 64
    - 32
    - 1
    - 1
  pvp-enabled: false
  drop-items-on-death: false # if set to true, players might be able to get items from last round if items aren't destroyed by lava
  # ^ if set to false, players won't be able to get other's item by killing other players
  reward:
    # Please enter valid material ID (All the material ID is in https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
    - "NETHERITE_INGOT"
    - "DIAMOND"
  reward-amount: # Enter the exact order following the item above
    - 5
    - 32
  reward-commands: # Enter a list of command that you want to execute in order to give the players the award
    # Available placeholders: %player%
    # If you don't need to execute any command, just leave it empty
    # ex.
    # "give %player% diamond 1"
    -
  ip: "play.minigames.net" # IP that will be displayed in game